<?php
echo "<!DOCTYPE HTML>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<!--Author: W3layouts Author URL: http://w3layouts.com License: Creative Commons Attribution 3.0 Unported License URL: http://creativecommons.org/licenses/by/3.0/ -->\n"; 
echo "  <title>Classy Login form Widget Flat Responsive Widget Template\n"; 
echo ":: w3layouts</title>\n"; 
echo "  <script src=\"js/jquery.min.js\"></script><!-- Custom Theme files -->\n"; 
echo "  <link href=\"css/style.css\" rel=\"stylesheet\"\n"; 
echo " type=\"text/css\" media=\"all\">\n"; 
echo "<!-- for-mobile-apps -->\n"; 
echo "  <meta http-equiv=\"Content-Type\"\n"; 
echo " content=\"text/html; charset=utf-8\">\n"; 
echo "  <meta name=\"viewport\"\n"; 
echo " content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n"; 
echo "  <meta http-equiv=\"Content-Type\"\n"; 
echo " content=\"text/html; charset=utf-8\">\n"; 
echo "  <meta name=\"keywords\"\n"; 
echo " content=\"Classy Login form Responsive, Login form web template, Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\">\n"; 
echo "<!-- //for-mobile-apps --><!--Google Fonts-->\n"; 
echo "  <link\n"; 
echo " href=\"//fonts.googleapis.com/css?family=Roboto+Condensed:400,700\"\n"; 
echo " rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "\n"; 
echo "<!--header start here-->\n"; 
echo "<div class=\"header\">\n"; 
echo "<div class=\"header-main\">\n"; 
echo "<h1>LOGIN TVU</h1>\n"; 
echo "<div class=\"header-bottom\">\n"; 
echo "<div class=\"header-right w3agile\">\n"; 
echo "<div class=\"header-left-bottom agileinfo\">\n"; 
echo "\n"; 
echo "<form action=\"ktdn.php\" method=\"post\"> <input\n"; 
echo " value=\"User name\" name=\"user\" onFocus=\"this.value = '';\"\n"; 
echo " onblur=\"if (this.value == '') {this.value = 'User name';}\"\n"; 
echo " type=\"text\"> <input value=\"Password\"\n"; 
echo " name=\"pass\" onFocus=\"this.value = '';\"\n"; 
echo " onblur=\"if (this.value == '') {this.value = 'password';}\"\n"; 
echo " type=\"password\">\n"; 
echo "\n"; 
echo "  <div class=\"remember\"> <span class=\"checkbox1\"><label\n"; 
echo " class=\"checkbox\"><input name=\"\" checked=\"checked\"\n"; 
echo " type=\"checkbox\"><i> </i>Remember\n"; 
echo "me</label> \n"; 
echo "  </span>\n"; 
echo "  <div class=\"clear\"> </div>\n"; 
echo "  </div>\n"; 
echo "  < <input  name=\"submit\" value=\"Login\" type=\"submit\"> </form>\n"; 
echo "\n"; 
echo "<div class=\"header-left-top\">\n"; 
echo "<div class=\"sign-up\"></div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>