<?php
echo "<table width=\"995\" height=\"233\" border=\"0\" align=\"center\">\n"; 
echo "  <tr>\n"; 
echo "    <td height=\"197\" colspan=\"6\"><img src=\"img/003.jpg\" width=\"986\" height=\"193\" /></td>\n"; 
echo "  </tr>\n"; 
echo "  <tr>\n"; 
echo "    <td width=\"118\" height=\"30\" bgcolor=\"#999999\"><div align=\"center\" class=\"style6\">\n"; 
echo "      <div align=\"center\"><a href=\"trangchu.php\" class=\"style8\">TRANG CH&#7910; </a></div>\n"; 
echo "    </div></td>\n"; 
echo "    <td width=\"162\" bgcolor=\"#999999\"><div align=\"center\" class=\"style6\">\n"; 
echo "      <div align=\"center\"><a href=\"danhmucsach.php\" class=\"style8\">DANH M&#7908;C S&Aacute;CH</a></div>\n"; 
echo "    </div></td>\n"; 
echo "    <td width=\"162\" bgcolor=\"#999999\"><div align=\"center\"><a href=\"tracuumuon.php\" class=\"style8\">TRA C&#7912;U M&#431;&#7906;N </a></div></td>\n"; 
echo "    <td width=\"163\" bgcolor=\"#999999\"><div align=\"center\"><a href=\"duyettrasach.php\" class=\"style8\">DUY&#7878;T TR&#7842; S&Aacute;CH </a></div></td>\n"; 
echo "    <td width=\"226\" bgcolor=\"#999999\"><form action=\"timkiem.php\" method=\"post\" name=\"form1\" class=\"style6\" id=\"form1\">\n"; 
echo "      <div align=\"center\">\n"; 
echo "        <input type=\"text\" name=\"textfield\" />\n"; 
echo "        <input type=\"submit\" value=\"T&igrave;m\" name=\"search\">\n"; 
echo "      </div>\n"; 
echo "    </form></td>\n"; 
echo "    <td width=\"138\" bgcolor=\"#999999\"><div align=\"center\" class=\"style6\">\n"; 
echo "      <div align=\"center\"><a href=\"dangxuat.php\" class=\"style8\">&#272;&#258;NG XU&#7844;T </a></div>\n"; 
echo "    </div></td>\n"; 
echo "  </tr>\n"; 
echo "</table>\n"; 
echo "<table width=\"995\" height=\"30\" border=\"0\" align=\"center\">\n"; 
echo "  <tr>\n"; 
echo "    <td width=\"173\" height=\"26\" bgcolor=\"#999999\"><div align=\"center\" class=\"style6\">\n"; 
echo "      <div align=\"center\"><a href=\"themsach.php\" class=\"style8\">TH&Ecirc;M S&Aacute;CH </a></div>\n"; 
echo "    </div></td>\n"; 
echo "    <td width=\"173\" bgcolor=\"#999999\"><div align=\"center\" class=\"style6\">\n"; 
echo "      <div align=\"center\"><a href=\"xoasach.php\" class=\"style8\">X&Oacute;A S&Aacute;CH </a></div>\n"; 
echo "    </div></td>\n"; 
echo "    <td width=\"222\" bgcolor=\"#999999\"><div align=\"center\"><a href=\"themtaikhoan.php\" class=\"style8\">TH&Ecirc;M T&Agrave;I KHO&#7842;N </a></div></td>\n"; 
echo "    <td width=\"191\" bgcolor=\"#999999\"><div align=\"center\"><a href=\"xoataikhoan.php\" class=\"style8\">X&Oacute;A T&Agrave;I KHO&#7842;N </a></div></td>\n"; 
echo "    <td width=\"214\" bgcolor=\"#999999\"><div align=\"center\"><a href=\"capnhattaikhoan.php\" class=\"style8\">C&#7852;P NH&#7852;T T&Agrave;I KHO&#7842;N</a></div></td>\n"; 
echo "  </tr>\n"; 
echo "</table>\n";
?>